
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Seller
 * 
 */
export type Seller = Prisma.SellerModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model Otp
 * 
 */
export type Otp = Prisma.OtpModel
/**
 * Model Plugin
 * 
 */
export type Plugin = Prisma.PluginModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Subcategory
 * 
 */
export type Subcategory = Prisma.SubcategoryModel
/**
 * Model Tag
 * 
 */
export type Tag = Prisma.TagModel
/**
 * Model PluginTag
 * 
 */
export type PluginTag = Prisma.PluginTagModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model LicenseKey
 * 
 */
export type LicenseKey = Prisma.LicenseKeyModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model Payout
 * 
 */
export type Payout = Prisma.PayoutModel
/**
 * Model PluginView
 * 
 */
export type PluginView = Prisma.PluginViewModel
