
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LicenseKey` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LicenseKey
 * 
 */
export type LicenseKeyModel = runtime.Types.Result.DefaultSelection<Prisma.$LicenseKeyPayload>

export type AggregateLicenseKey = {
  _count: LicenseKeyCountAggregateOutputType | null
  _avg: LicenseKeyAvgAggregateOutputType | null
  _sum: LicenseKeySumAggregateOutputType | null
  _min: LicenseKeyMinAggregateOutputType | null
  _max: LicenseKeyMaxAggregateOutputType | null
}

export type LicenseKeyAvgAggregateOutputType = {
  downloadCount: number | null
  maxDownloads: number | null
}

export type LicenseKeySumAggregateOutputType = {
  downloadCount: number | null
  maxDownloads: number | null
}

export type LicenseKeyMinAggregateOutputType = {
  id: string | null
  key: string | null
  orderId: string | null
  pluginId: string | null
  downloadCount: number | null
  maxDownloads: number | null
  lastDownloadAt: Date | null
  isActive: boolean | null
  createdAt: Date | null
  expiresAt: Date | null
}

export type LicenseKeyMaxAggregateOutputType = {
  id: string | null
  key: string | null
  orderId: string | null
  pluginId: string | null
  downloadCount: number | null
  maxDownloads: number | null
  lastDownloadAt: Date | null
  isActive: boolean | null
  createdAt: Date | null
  expiresAt: Date | null
}

export type LicenseKeyCountAggregateOutputType = {
  id: number
  key: number
  orderId: number
  pluginId: number
  downloadCount: number
  maxDownloads: number
  lastDownloadAt: number
  isActive: number
  createdAt: number
  expiresAt: number
  _all: number
}


export type LicenseKeyAvgAggregateInputType = {
  downloadCount?: true
  maxDownloads?: true
}

export type LicenseKeySumAggregateInputType = {
  downloadCount?: true
  maxDownloads?: true
}

export type LicenseKeyMinAggregateInputType = {
  id?: true
  key?: true
  orderId?: true
  pluginId?: true
  downloadCount?: true
  maxDownloads?: true
  lastDownloadAt?: true
  isActive?: true
  createdAt?: true
  expiresAt?: true
}

export type LicenseKeyMaxAggregateInputType = {
  id?: true
  key?: true
  orderId?: true
  pluginId?: true
  downloadCount?: true
  maxDownloads?: true
  lastDownloadAt?: true
  isActive?: true
  createdAt?: true
  expiresAt?: true
}

export type LicenseKeyCountAggregateInputType = {
  id?: true
  key?: true
  orderId?: true
  pluginId?: true
  downloadCount?: true
  maxDownloads?: true
  lastDownloadAt?: true
  isActive?: true
  createdAt?: true
  expiresAt?: true
  _all?: true
}

export type LicenseKeyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LicenseKey to aggregate.
   */
  where?: Prisma.LicenseKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LicenseKeys to fetch.
   */
  orderBy?: Prisma.LicenseKeyOrderByWithRelationInput | Prisma.LicenseKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LicenseKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LicenseKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LicenseKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LicenseKeys
  **/
  _count?: true | LicenseKeyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LicenseKeyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LicenseKeySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LicenseKeyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LicenseKeyMaxAggregateInputType
}

export type GetLicenseKeyAggregateType<T extends LicenseKeyAggregateArgs> = {
      [P in keyof T & keyof AggregateLicenseKey]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLicenseKey[P]>
    : Prisma.GetScalarType<T[P], AggregateLicenseKey[P]>
}




export type LicenseKeyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LicenseKeyWhereInput
  orderBy?: Prisma.LicenseKeyOrderByWithAggregationInput | Prisma.LicenseKeyOrderByWithAggregationInput[]
  by: Prisma.LicenseKeyScalarFieldEnum[] | Prisma.LicenseKeyScalarFieldEnum
  having?: Prisma.LicenseKeyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LicenseKeyCountAggregateInputType | true
  _avg?: LicenseKeyAvgAggregateInputType
  _sum?: LicenseKeySumAggregateInputType
  _min?: LicenseKeyMinAggregateInputType
  _max?: LicenseKeyMaxAggregateInputType
}

export type LicenseKeyGroupByOutputType = {
  id: string
  key: string
  orderId: string
  pluginId: string
  downloadCount: number
  maxDownloads: number
  lastDownloadAt: Date | null
  isActive: boolean
  createdAt: Date
  expiresAt: Date | null
  _count: LicenseKeyCountAggregateOutputType | null
  _avg: LicenseKeyAvgAggregateOutputType | null
  _sum: LicenseKeySumAggregateOutputType | null
  _min: LicenseKeyMinAggregateOutputType | null
  _max: LicenseKeyMaxAggregateOutputType | null
}

type GetLicenseKeyGroupByPayload<T extends LicenseKeyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LicenseKeyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LicenseKeyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LicenseKeyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LicenseKeyGroupByOutputType[P]>
      }
    >
  >



export type LicenseKeyWhereInput = {
  AND?: Prisma.LicenseKeyWhereInput | Prisma.LicenseKeyWhereInput[]
  OR?: Prisma.LicenseKeyWhereInput[]
  NOT?: Prisma.LicenseKeyWhereInput | Prisma.LicenseKeyWhereInput[]
  id?: Prisma.StringFilter<"LicenseKey"> | string
  key?: Prisma.StringFilter<"LicenseKey"> | string
  orderId?: Prisma.StringFilter<"LicenseKey"> | string
  pluginId?: Prisma.StringFilter<"LicenseKey"> | string
  downloadCount?: Prisma.IntFilter<"LicenseKey"> | number
  maxDownloads?: Prisma.IntFilter<"LicenseKey"> | number
  lastDownloadAt?: Prisma.DateTimeNullableFilter<"LicenseKey"> | Date | string | null
  isActive?: Prisma.BoolFilter<"LicenseKey"> | boolean
  createdAt?: Prisma.DateTimeFilter<"LicenseKey"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"LicenseKey"> | Date | string | null
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
}

export type LicenseKeyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  maxDownloads?: Prisma.SortOrder
  lastDownloadAt?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.OrderOrderByWithRelationInput
}

export type LicenseKeyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  key?: string
  AND?: Prisma.LicenseKeyWhereInput | Prisma.LicenseKeyWhereInput[]
  OR?: Prisma.LicenseKeyWhereInput[]
  NOT?: Prisma.LicenseKeyWhereInput | Prisma.LicenseKeyWhereInput[]
  orderId?: Prisma.StringFilter<"LicenseKey"> | string
  pluginId?: Prisma.StringFilter<"LicenseKey"> | string
  downloadCount?: Prisma.IntFilter<"LicenseKey"> | number
  maxDownloads?: Prisma.IntFilter<"LicenseKey"> | number
  lastDownloadAt?: Prisma.DateTimeNullableFilter<"LicenseKey"> | Date | string | null
  isActive?: Prisma.BoolFilter<"LicenseKey"> | boolean
  createdAt?: Prisma.DateTimeFilter<"LicenseKey"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"LicenseKey"> | Date | string | null
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
}, "id" | "key">

export type LicenseKeyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  maxDownloads?: Prisma.SortOrder
  lastDownloadAt?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.LicenseKeyCountOrderByAggregateInput
  _avg?: Prisma.LicenseKeyAvgOrderByAggregateInput
  _max?: Prisma.LicenseKeyMaxOrderByAggregateInput
  _min?: Prisma.LicenseKeyMinOrderByAggregateInput
  _sum?: Prisma.LicenseKeySumOrderByAggregateInput
}

export type LicenseKeyScalarWhereWithAggregatesInput = {
  AND?: Prisma.LicenseKeyScalarWhereWithAggregatesInput | Prisma.LicenseKeyScalarWhereWithAggregatesInput[]
  OR?: Prisma.LicenseKeyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LicenseKeyScalarWhereWithAggregatesInput | Prisma.LicenseKeyScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LicenseKey"> | string
  key?: Prisma.StringWithAggregatesFilter<"LicenseKey"> | string
  orderId?: Prisma.StringWithAggregatesFilter<"LicenseKey"> | string
  pluginId?: Prisma.StringWithAggregatesFilter<"LicenseKey"> | string
  downloadCount?: Prisma.IntWithAggregatesFilter<"LicenseKey"> | number
  maxDownloads?: Prisma.IntWithAggregatesFilter<"LicenseKey"> | number
  lastDownloadAt?: Prisma.DateTimeNullableWithAggregatesFilter<"LicenseKey"> | Date | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"LicenseKey"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LicenseKey"> | Date | string
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"LicenseKey"> | Date | string | null
}

export type LicenseKeyCreateInput = {
  id?: string
  key: string
  pluginId: string
  downloadCount?: number
  maxDownloads?: number
  lastDownloadAt?: Date | string | null
  isActive?: boolean
  createdAt?: Date | string
  expiresAt?: Date | string | null
  order: Prisma.OrderCreateNestedOneWithoutLicenseKeysInput
}

export type LicenseKeyUncheckedCreateInput = {
  id?: string
  key: string
  orderId: string
  pluginId: string
  downloadCount?: number
  maxDownloads?: number
  lastDownloadAt?: Date | string | null
  isActive?: boolean
  createdAt?: Date | string
  expiresAt?: Date | string | null
}

export type LicenseKeyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  maxDownloads?: Prisma.IntFieldUpdateOperationsInput | number
  lastDownloadAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  order?: Prisma.OrderUpdateOneRequiredWithoutLicenseKeysNestedInput
}

export type LicenseKeyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  maxDownloads?: Prisma.IntFieldUpdateOperationsInput | number
  lastDownloadAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LicenseKeyCreateManyInput = {
  id?: string
  key: string
  orderId: string
  pluginId: string
  downloadCount?: number
  maxDownloads?: number
  lastDownloadAt?: Date | string | null
  isActive?: boolean
  createdAt?: Date | string
  expiresAt?: Date | string | null
}

export type LicenseKeyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  maxDownloads?: Prisma.IntFieldUpdateOperationsInput | number
  lastDownloadAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LicenseKeyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  maxDownloads?: Prisma.IntFieldUpdateOperationsInput | number
  lastDownloadAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LicenseKeyListRelationFilter = {
  every?: Prisma.LicenseKeyWhereInput
  some?: Prisma.LicenseKeyWhereInput
  none?: Prisma.LicenseKeyWhereInput
}

export type LicenseKeyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LicenseKeyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  maxDownloads?: Prisma.SortOrder
  lastDownloadAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type LicenseKeyAvgOrderByAggregateInput = {
  downloadCount?: Prisma.SortOrder
  maxDownloads?: Prisma.SortOrder
}

export type LicenseKeyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  maxDownloads?: Prisma.SortOrder
  lastDownloadAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type LicenseKeyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  downloadCount?: Prisma.SortOrder
  maxDownloads?: Prisma.SortOrder
  lastDownloadAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type LicenseKeySumOrderByAggregateInput = {
  downloadCount?: Prisma.SortOrder
  maxDownloads?: Prisma.SortOrder
}

export type LicenseKeyCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.LicenseKeyCreateWithoutOrderInput, Prisma.LicenseKeyUncheckedCreateWithoutOrderInput> | Prisma.LicenseKeyCreateWithoutOrderInput[] | Prisma.LicenseKeyUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.LicenseKeyCreateOrConnectWithoutOrderInput | Prisma.LicenseKeyCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.LicenseKeyCreateManyOrderInputEnvelope
  connect?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
}

export type LicenseKeyUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.LicenseKeyCreateWithoutOrderInput, Prisma.LicenseKeyUncheckedCreateWithoutOrderInput> | Prisma.LicenseKeyCreateWithoutOrderInput[] | Prisma.LicenseKeyUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.LicenseKeyCreateOrConnectWithoutOrderInput | Prisma.LicenseKeyCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.LicenseKeyCreateManyOrderInputEnvelope
  connect?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
}

export type LicenseKeyUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.LicenseKeyCreateWithoutOrderInput, Prisma.LicenseKeyUncheckedCreateWithoutOrderInput> | Prisma.LicenseKeyCreateWithoutOrderInput[] | Prisma.LicenseKeyUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.LicenseKeyCreateOrConnectWithoutOrderInput | Prisma.LicenseKeyCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.LicenseKeyUpsertWithWhereUniqueWithoutOrderInput | Prisma.LicenseKeyUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.LicenseKeyCreateManyOrderInputEnvelope
  set?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
  disconnect?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
  delete?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
  connect?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
  update?: Prisma.LicenseKeyUpdateWithWhereUniqueWithoutOrderInput | Prisma.LicenseKeyUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.LicenseKeyUpdateManyWithWhereWithoutOrderInput | Prisma.LicenseKeyUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.LicenseKeyScalarWhereInput | Prisma.LicenseKeyScalarWhereInput[]
}

export type LicenseKeyUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.LicenseKeyCreateWithoutOrderInput, Prisma.LicenseKeyUncheckedCreateWithoutOrderInput> | Prisma.LicenseKeyCreateWithoutOrderInput[] | Prisma.LicenseKeyUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.LicenseKeyCreateOrConnectWithoutOrderInput | Prisma.LicenseKeyCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.LicenseKeyUpsertWithWhereUniqueWithoutOrderInput | Prisma.LicenseKeyUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.LicenseKeyCreateManyOrderInputEnvelope
  set?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
  disconnect?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
  delete?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
  connect?: Prisma.LicenseKeyWhereUniqueInput | Prisma.LicenseKeyWhereUniqueInput[]
  update?: Prisma.LicenseKeyUpdateWithWhereUniqueWithoutOrderInput | Prisma.LicenseKeyUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.LicenseKeyUpdateManyWithWhereWithoutOrderInput | Prisma.LicenseKeyUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.LicenseKeyScalarWhereInput | Prisma.LicenseKeyScalarWhereInput[]
}

export type LicenseKeyCreateWithoutOrderInput = {
  id?: string
  key: string
  pluginId: string
  downloadCount?: number
  maxDownloads?: number
  lastDownloadAt?: Date | string | null
  isActive?: boolean
  createdAt?: Date | string
  expiresAt?: Date | string | null
}

export type LicenseKeyUncheckedCreateWithoutOrderInput = {
  id?: string
  key: string
  pluginId: string
  downloadCount?: number
  maxDownloads?: number
  lastDownloadAt?: Date | string | null
  isActive?: boolean
  createdAt?: Date | string
  expiresAt?: Date | string | null
}

export type LicenseKeyCreateOrConnectWithoutOrderInput = {
  where: Prisma.LicenseKeyWhereUniqueInput
  create: Prisma.XOR<Prisma.LicenseKeyCreateWithoutOrderInput, Prisma.LicenseKeyUncheckedCreateWithoutOrderInput>
}

export type LicenseKeyCreateManyOrderInputEnvelope = {
  data: Prisma.LicenseKeyCreateManyOrderInput | Prisma.LicenseKeyCreateManyOrderInput[]
  skipDuplicates?: boolean
}

export type LicenseKeyUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.LicenseKeyWhereUniqueInput
  update: Prisma.XOR<Prisma.LicenseKeyUpdateWithoutOrderInput, Prisma.LicenseKeyUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.LicenseKeyCreateWithoutOrderInput, Prisma.LicenseKeyUncheckedCreateWithoutOrderInput>
}

export type LicenseKeyUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.LicenseKeyWhereUniqueInput
  data: Prisma.XOR<Prisma.LicenseKeyUpdateWithoutOrderInput, Prisma.LicenseKeyUncheckedUpdateWithoutOrderInput>
}

export type LicenseKeyUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.LicenseKeyScalarWhereInput
  data: Prisma.XOR<Prisma.LicenseKeyUpdateManyMutationInput, Prisma.LicenseKeyUncheckedUpdateManyWithoutOrderInput>
}

export type LicenseKeyScalarWhereInput = {
  AND?: Prisma.LicenseKeyScalarWhereInput | Prisma.LicenseKeyScalarWhereInput[]
  OR?: Prisma.LicenseKeyScalarWhereInput[]
  NOT?: Prisma.LicenseKeyScalarWhereInput | Prisma.LicenseKeyScalarWhereInput[]
  id?: Prisma.StringFilter<"LicenseKey"> | string
  key?: Prisma.StringFilter<"LicenseKey"> | string
  orderId?: Prisma.StringFilter<"LicenseKey"> | string
  pluginId?: Prisma.StringFilter<"LicenseKey"> | string
  downloadCount?: Prisma.IntFilter<"LicenseKey"> | number
  maxDownloads?: Prisma.IntFilter<"LicenseKey"> | number
  lastDownloadAt?: Prisma.DateTimeNullableFilter<"LicenseKey"> | Date | string | null
  isActive?: Prisma.BoolFilter<"LicenseKey"> | boolean
  createdAt?: Prisma.DateTimeFilter<"LicenseKey"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"LicenseKey"> | Date | string | null
}

export type LicenseKeyCreateManyOrderInput = {
  id?: string
  key: string
  pluginId: string
  downloadCount?: number
  maxDownloads?: number
  lastDownloadAt?: Date | string | null
  isActive?: boolean
  createdAt?: Date | string
  expiresAt?: Date | string | null
}

export type LicenseKeyUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  maxDownloads?: Prisma.IntFieldUpdateOperationsInput | number
  lastDownloadAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LicenseKeyUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  maxDownloads?: Prisma.IntFieldUpdateOperationsInput | number
  lastDownloadAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LicenseKeyUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  downloadCount?: Prisma.IntFieldUpdateOperationsInput | number
  maxDownloads?: Prisma.IntFieldUpdateOperationsInput | number
  lastDownloadAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type LicenseKeySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  orderId?: boolean
  pluginId?: boolean
  downloadCount?: boolean
  maxDownloads?: boolean
  lastDownloadAt?: boolean
  isActive?: boolean
  createdAt?: boolean
  expiresAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["licenseKey"]>

export type LicenseKeySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  orderId?: boolean
  pluginId?: boolean
  downloadCount?: boolean
  maxDownloads?: boolean
  lastDownloadAt?: boolean
  isActive?: boolean
  createdAt?: boolean
  expiresAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["licenseKey"]>

export type LicenseKeySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  orderId?: boolean
  pluginId?: boolean
  downloadCount?: boolean
  maxDownloads?: boolean
  lastDownloadAt?: boolean
  isActive?: boolean
  createdAt?: boolean
  expiresAt?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["licenseKey"]>

export type LicenseKeySelectScalar = {
  id?: boolean
  key?: boolean
  orderId?: boolean
  pluginId?: boolean
  downloadCount?: boolean
  maxDownloads?: boolean
  lastDownloadAt?: boolean
  isActive?: boolean
  createdAt?: boolean
  expiresAt?: boolean
}

export type LicenseKeyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "orderId" | "pluginId" | "downloadCount" | "maxDownloads" | "lastDownloadAt" | "isActive" | "createdAt" | "expiresAt", ExtArgs["result"]["licenseKey"]>
export type LicenseKeyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type LicenseKeyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type LicenseKeyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}

export type $LicenseKeyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LicenseKey"
  objects: {
    order: Prisma.$OrderPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    key: string
    orderId: string
    pluginId: string
    downloadCount: number
    maxDownloads: number
    lastDownloadAt: Date | null
    isActive: boolean
    createdAt: Date
    expiresAt: Date | null
  }, ExtArgs["result"]["licenseKey"]>
  composites: {}
}

export type LicenseKeyGetPayload<S extends boolean | null | undefined | LicenseKeyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload, S>

export type LicenseKeyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LicenseKeyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LicenseKeyCountAggregateInputType | true
  }

export interface LicenseKeyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LicenseKey'], meta: { name: 'LicenseKey' } }
  /**
   * Find zero or one LicenseKey that matches the filter.
   * @param {LicenseKeyFindUniqueArgs} args - Arguments to find a LicenseKey
   * @example
   * // Get one LicenseKey
   * const licenseKey = await prisma.licenseKey.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LicenseKeyFindUniqueArgs>(args: Prisma.SelectSubset<T, LicenseKeyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LicenseKeyClient<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LicenseKey that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LicenseKeyFindUniqueOrThrowArgs} args - Arguments to find a LicenseKey
   * @example
   * // Get one LicenseKey
   * const licenseKey = await prisma.licenseKey.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LicenseKeyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LicenseKeyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LicenseKeyClient<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LicenseKey that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseKeyFindFirstArgs} args - Arguments to find a LicenseKey
   * @example
   * // Get one LicenseKey
   * const licenseKey = await prisma.licenseKey.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LicenseKeyFindFirstArgs>(args?: Prisma.SelectSubset<T, LicenseKeyFindFirstArgs<ExtArgs>>): Prisma.Prisma__LicenseKeyClient<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LicenseKey that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseKeyFindFirstOrThrowArgs} args - Arguments to find a LicenseKey
   * @example
   * // Get one LicenseKey
   * const licenseKey = await prisma.licenseKey.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LicenseKeyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LicenseKeyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LicenseKeyClient<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LicenseKeys that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseKeyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LicenseKeys
   * const licenseKeys = await prisma.licenseKey.findMany()
   * 
   * // Get first 10 LicenseKeys
   * const licenseKeys = await prisma.licenseKey.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const licenseKeyWithIdOnly = await prisma.licenseKey.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LicenseKeyFindManyArgs>(args?: Prisma.SelectSubset<T, LicenseKeyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LicenseKey.
   * @param {LicenseKeyCreateArgs} args - Arguments to create a LicenseKey.
   * @example
   * // Create one LicenseKey
   * const LicenseKey = await prisma.licenseKey.create({
   *   data: {
   *     // ... data to create a LicenseKey
   *   }
   * })
   * 
   */
  create<T extends LicenseKeyCreateArgs>(args: Prisma.SelectSubset<T, LicenseKeyCreateArgs<ExtArgs>>): Prisma.Prisma__LicenseKeyClient<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LicenseKeys.
   * @param {LicenseKeyCreateManyArgs} args - Arguments to create many LicenseKeys.
   * @example
   * // Create many LicenseKeys
   * const licenseKey = await prisma.licenseKey.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LicenseKeyCreateManyArgs>(args?: Prisma.SelectSubset<T, LicenseKeyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LicenseKeys and returns the data saved in the database.
   * @param {LicenseKeyCreateManyAndReturnArgs} args - Arguments to create many LicenseKeys.
   * @example
   * // Create many LicenseKeys
   * const licenseKey = await prisma.licenseKey.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LicenseKeys and only return the `id`
   * const licenseKeyWithIdOnly = await prisma.licenseKey.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LicenseKeyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LicenseKeyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LicenseKey.
   * @param {LicenseKeyDeleteArgs} args - Arguments to delete one LicenseKey.
   * @example
   * // Delete one LicenseKey
   * const LicenseKey = await prisma.licenseKey.delete({
   *   where: {
   *     // ... filter to delete one LicenseKey
   *   }
   * })
   * 
   */
  delete<T extends LicenseKeyDeleteArgs>(args: Prisma.SelectSubset<T, LicenseKeyDeleteArgs<ExtArgs>>): Prisma.Prisma__LicenseKeyClient<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LicenseKey.
   * @param {LicenseKeyUpdateArgs} args - Arguments to update one LicenseKey.
   * @example
   * // Update one LicenseKey
   * const licenseKey = await prisma.licenseKey.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LicenseKeyUpdateArgs>(args: Prisma.SelectSubset<T, LicenseKeyUpdateArgs<ExtArgs>>): Prisma.Prisma__LicenseKeyClient<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LicenseKeys.
   * @param {LicenseKeyDeleteManyArgs} args - Arguments to filter LicenseKeys to delete.
   * @example
   * // Delete a few LicenseKeys
   * const { count } = await prisma.licenseKey.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LicenseKeyDeleteManyArgs>(args?: Prisma.SelectSubset<T, LicenseKeyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LicenseKeys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseKeyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LicenseKeys
   * const licenseKey = await prisma.licenseKey.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LicenseKeyUpdateManyArgs>(args: Prisma.SelectSubset<T, LicenseKeyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LicenseKeys and returns the data updated in the database.
   * @param {LicenseKeyUpdateManyAndReturnArgs} args - Arguments to update many LicenseKeys.
   * @example
   * // Update many LicenseKeys
   * const licenseKey = await prisma.licenseKey.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LicenseKeys and only return the `id`
   * const licenseKeyWithIdOnly = await prisma.licenseKey.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LicenseKeyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LicenseKeyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LicenseKey.
   * @param {LicenseKeyUpsertArgs} args - Arguments to update or create a LicenseKey.
   * @example
   * // Update or create a LicenseKey
   * const licenseKey = await prisma.licenseKey.upsert({
   *   create: {
   *     // ... data to create a LicenseKey
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LicenseKey we want to update
   *   }
   * })
   */
  upsert<T extends LicenseKeyUpsertArgs>(args: Prisma.SelectSubset<T, LicenseKeyUpsertArgs<ExtArgs>>): Prisma.Prisma__LicenseKeyClient<runtime.Types.Result.GetResult<Prisma.$LicenseKeyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LicenseKeys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseKeyCountArgs} args - Arguments to filter LicenseKeys to count.
   * @example
   * // Count the number of LicenseKeys
   * const count = await prisma.licenseKey.count({
   *   where: {
   *     // ... the filter for the LicenseKeys we want to count
   *   }
   * })
  **/
  count<T extends LicenseKeyCountArgs>(
    args?: Prisma.Subset<T, LicenseKeyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LicenseKeyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LicenseKey.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseKeyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LicenseKeyAggregateArgs>(args: Prisma.Subset<T, LicenseKeyAggregateArgs>): Prisma.PrismaPromise<GetLicenseKeyAggregateType<T>>

  /**
   * Group by LicenseKey.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LicenseKeyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LicenseKeyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LicenseKeyGroupByArgs['orderBy'] }
      : { orderBy?: LicenseKeyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LicenseKeyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLicenseKeyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LicenseKey model
 */
readonly fields: LicenseKeyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LicenseKey.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LicenseKeyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.OrderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrderDefaultArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LicenseKey model
 */
export interface LicenseKeyFieldRefs {
  readonly id: Prisma.FieldRef<"LicenseKey", 'String'>
  readonly key: Prisma.FieldRef<"LicenseKey", 'String'>
  readonly orderId: Prisma.FieldRef<"LicenseKey", 'String'>
  readonly pluginId: Prisma.FieldRef<"LicenseKey", 'String'>
  readonly downloadCount: Prisma.FieldRef<"LicenseKey", 'Int'>
  readonly maxDownloads: Prisma.FieldRef<"LicenseKey", 'Int'>
  readonly lastDownloadAt: Prisma.FieldRef<"LicenseKey", 'DateTime'>
  readonly isActive: Prisma.FieldRef<"LicenseKey", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"LicenseKey", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"LicenseKey", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LicenseKey findUnique
 */
export type LicenseKeyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
  /**
   * Filter, which LicenseKey to fetch.
   */
  where: Prisma.LicenseKeyWhereUniqueInput
}

/**
 * LicenseKey findUniqueOrThrow
 */
export type LicenseKeyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
  /**
   * Filter, which LicenseKey to fetch.
   */
  where: Prisma.LicenseKeyWhereUniqueInput
}

/**
 * LicenseKey findFirst
 */
export type LicenseKeyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
  /**
   * Filter, which LicenseKey to fetch.
   */
  where?: Prisma.LicenseKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LicenseKeys to fetch.
   */
  orderBy?: Prisma.LicenseKeyOrderByWithRelationInput | Prisma.LicenseKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LicenseKeys.
   */
  cursor?: Prisma.LicenseKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LicenseKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LicenseKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LicenseKeys.
   */
  distinct?: Prisma.LicenseKeyScalarFieldEnum | Prisma.LicenseKeyScalarFieldEnum[]
}

/**
 * LicenseKey findFirstOrThrow
 */
export type LicenseKeyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
  /**
   * Filter, which LicenseKey to fetch.
   */
  where?: Prisma.LicenseKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LicenseKeys to fetch.
   */
  orderBy?: Prisma.LicenseKeyOrderByWithRelationInput | Prisma.LicenseKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LicenseKeys.
   */
  cursor?: Prisma.LicenseKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LicenseKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LicenseKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LicenseKeys.
   */
  distinct?: Prisma.LicenseKeyScalarFieldEnum | Prisma.LicenseKeyScalarFieldEnum[]
}

/**
 * LicenseKey findMany
 */
export type LicenseKeyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
  /**
   * Filter, which LicenseKeys to fetch.
   */
  where?: Prisma.LicenseKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LicenseKeys to fetch.
   */
  orderBy?: Prisma.LicenseKeyOrderByWithRelationInput | Prisma.LicenseKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LicenseKeys.
   */
  cursor?: Prisma.LicenseKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LicenseKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LicenseKeys.
   */
  skip?: number
  distinct?: Prisma.LicenseKeyScalarFieldEnum | Prisma.LicenseKeyScalarFieldEnum[]
}

/**
 * LicenseKey create
 */
export type LicenseKeyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
  /**
   * The data needed to create a LicenseKey.
   */
  data: Prisma.XOR<Prisma.LicenseKeyCreateInput, Prisma.LicenseKeyUncheckedCreateInput>
}

/**
 * LicenseKey createMany
 */
export type LicenseKeyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LicenseKeys.
   */
  data: Prisma.LicenseKeyCreateManyInput | Prisma.LicenseKeyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LicenseKey createManyAndReturn
 */
export type LicenseKeyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * The data used to create many LicenseKeys.
   */
  data: Prisma.LicenseKeyCreateManyInput | Prisma.LicenseKeyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LicenseKey update
 */
export type LicenseKeyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
  /**
   * The data needed to update a LicenseKey.
   */
  data: Prisma.XOR<Prisma.LicenseKeyUpdateInput, Prisma.LicenseKeyUncheckedUpdateInput>
  /**
   * Choose, which LicenseKey to update.
   */
  where: Prisma.LicenseKeyWhereUniqueInput
}

/**
 * LicenseKey updateMany
 */
export type LicenseKeyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LicenseKeys.
   */
  data: Prisma.XOR<Prisma.LicenseKeyUpdateManyMutationInput, Prisma.LicenseKeyUncheckedUpdateManyInput>
  /**
   * Filter which LicenseKeys to update
   */
  where?: Prisma.LicenseKeyWhereInput
  /**
   * Limit how many LicenseKeys to update.
   */
  limit?: number
}

/**
 * LicenseKey updateManyAndReturn
 */
export type LicenseKeyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * The data used to update LicenseKeys.
   */
  data: Prisma.XOR<Prisma.LicenseKeyUpdateManyMutationInput, Prisma.LicenseKeyUncheckedUpdateManyInput>
  /**
   * Filter which LicenseKeys to update
   */
  where?: Prisma.LicenseKeyWhereInput
  /**
   * Limit how many LicenseKeys to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LicenseKey upsert
 */
export type LicenseKeyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
  /**
   * The filter to search for the LicenseKey to update in case it exists.
   */
  where: Prisma.LicenseKeyWhereUniqueInput
  /**
   * In case the LicenseKey found by the `where` argument doesn't exist, create a new LicenseKey with this data.
   */
  create: Prisma.XOR<Prisma.LicenseKeyCreateInput, Prisma.LicenseKeyUncheckedCreateInput>
  /**
   * In case the LicenseKey was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LicenseKeyUpdateInput, Prisma.LicenseKeyUncheckedUpdateInput>
}

/**
 * LicenseKey delete
 */
export type LicenseKeyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
  /**
   * Filter which LicenseKey to delete.
   */
  where: Prisma.LicenseKeyWhereUniqueInput
}

/**
 * LicenseKey deleteMany
 */
export type LicenseKeyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LicenseKeys to delete
   */
  where?: Prisma.LicenseKeyWhereInput
  /**
   * Limit how many LicenseKeys to delete.
   */
  limit?: number
}

/**
 * LicenseKey without action
 */
export type LicenseKeyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LicenseKey
   */
  select?: Prisma.LicenseKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LicenseKey
   */
  omit?: Prisma.LicenseKeyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LicenseKeyInclude<ExtArgs> | null
}
