
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OTP` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OTP
 * 
 */
export type OTPModel = runtime.Types.Result.DefaultSelection<Prisma.$OTPPayload>

export type AggregateOTP = {
  _count: OTPCountAggregateOutputType | null
  _min: OTPMinAggregateOutputType | null
  _max: OTPMaxAggregateOutputType | null
}

export type OTPMinAggregateOutputType = {
  id: string | null
  email: string | null
  hashedCode: string | null
  createdAt: Date | null
  expiresAt: Date | null
  consumed: boolean | null
}

export type OTPMaxAggregateOutputType = {
  id: string | null
  email: string | null
  hashedCode: string | null
  createdAt: Date | null
  expiresAt: Date | null
  consumed: boolean | null
}

export type OTPCountAggregateOutputType = {
  id: number
  email: number
  hashedCode: number
  createdAt: number
  expiresAt: number
  consumed: number
  _all: number
}


export type OTPMinAggregateInputType = {
  id?: true
  email?: true
  hashedCode?: true
  createdAt?: true
  expiresAt?: true
  consumed?: true
}

export type OTPMaxAggregateInputType = {
  id?: true
  email?: true
  hashedCode?: true
  createdAt?: true
  expiresAt?: true
  consumed?: true
}

export type OTPCountAggregateInputType = {
  id?: true
  email?: true
  hashedCode?: true
  createdAt?: true
  expiresAt?: true
  consumed?: true
  _all?: true
}

export type OTPAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OTP to aggregate.
   */
  where?: Prisma.OTPWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OTPS to fetch.
   */
  orderBy?: Prisma.OTPOrderByWithRelationInput | Prisma.OTPOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OTPWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OTPS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OTPS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OTPS
  **/
  _count?: true | OTPCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OTPMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OTPMaxAggregateInputType
}

export type GetOTPAggregateType<T extends OTPAggregateArgs> = {
      [P in keyof T & keyof AggregateOTP]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOTP[P]>
    : Prisma.GetScalarType<T[P], AggregateOTP[P]>
}




export type OTPGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OTPWhereInput
  orderBy?: Prisma.OTPOrderByWithAggregationInput | Prisma.OTPOrderByWithAggregationInput[]
  by: Prisma.OTPScalarFieldEnum[] | Prisma.OTPScalarFieldEnum
  having?: Prisma.OTPScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OTPCountAggregateInputType | true
  _min?: OTPMinAggregateInputType
  _max?: OTPMaxAggregateInputType
}

export type OTPGroupByOutputType = {
  id: string
  email: string
  hashedCode: string
  createdAt: Date
  expiresAt: Date
  consumed: boolean
  _count: OTPCountAggregateOutputType | null
  _min: OTPMinAggregateOutputType | null
  _max: OTPMaxAggregateOutputType | null
}

type GetOTPGroupByPayload<T extends OTPGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OTPGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OTPGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OTPGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OTPGroupByOutputType[P]>
      }
    >
  >



export type OTPWhereInput = {
  AND?: Prisma.OTPWhereInput | Prisma.OTPWhereInput[]
  OR?: Prisma.OTPWhereInput[]
  NOT?: Prisma.OTPWhereInput | Prisma.OTPWhereInput[]
  id?: Prisma.StringFilter<"OTP"> | string
  email?: Prisma.StringFilter<"OTP"> | string
  hashedCode?: Prisma.StringFilter<"OTP"> | string
  createdAt?: Prisma.DateTimeFilter<"OTP"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"OTP"> | Date | string
  consumed?: Prisma.BoolFilter<"OTP"> | boolean
}

export type OTPOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashedCode?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  consumed?: Prisma.SortOrder
}

export type OTPWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.OTPWhereInput | Prisma.OTPWhereInput[]
  OR?: Prisma.OTPWhereInput[]
  NOT?: Prisma.OTPWhereInput | Prisma.OTPWhereInput[]
  email?: Prisma.StringFilter<"OTP"> | string
  hashedCode?: Prisma.StringFilter<"OTP"> | string
  createdAt?: Prisma.DateTimeFilter<"OTP"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"OTP"> | Date | string
  consumed?: Prisma.BoolFilter<"OTP"> | boolean
}, "id">

export type OTPOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashedCode?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  consumed?: Prisma.SortOrder
  _count?: Prisma.OTPCountOrderByAggregateInput
  _max?: Prisma.OTPMaxOrderByAggregateInput
  _min?: Prisma.OTPMinOrderByAggregateInput
}

export type OTPScalarWhereWithAggregatesInput = {
  AND?: Prisma.OTPScalarWhereWithAggregatesInput | Prisma.OTPScalarWhereWithAggregatesInput[]
  OR?: Prisma.OTPScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OTPScalarWhereWithAggregatesInput | Prisma.OTPScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OTP"> | string
  email?: Prisma.StringWithAggregatesFilter<"OTP"> | string
  hashedCode?: Prisma.StringWithAggregatesFilter<"OTP"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OTP"> | Date | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"OTP"> | Date | string
  consumed?: Prisma.BoolWithAggregatesFilter<"OTP"> | boolean
}

export type OTPCreateInput = {
  id?: string
  email: string
  hashedCode: string
  createdAt?: Date | string
  expiresAt: Date | string
  consumed?: boolean
}

export type OTPUncheckedCreateInput = {
  id?: string
  email: string
  hashedCode: string
  createdAt?: Date | string
  expiresAt: Date | string
  consumed?: boolean
}

export type OTPUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashedCode?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consumed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type OTPUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashedCode?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consumed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type OTPCreateManyInput = {
  id?: string
  email: string
  hashedCode: string
  createdAt?: Date | string
  expiresAt: Date | string
  consumed?: boolean
}

export type OTPUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashedCode?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consumed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type OTPUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  hashedCode?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  consumed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type OTPCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashedCode?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  consumed?: Prisma.SortOrder
}

export type OTPMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashedCode?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  consumed?: Prisma.SortOrder
}

export type OTPMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  hashedCode?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  consumed?: Prisma.SortOrder
}



export type OTPSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  hashedCode?: boolean
  createdAt?: boolean
  expiresAt?: boolean
  consumed?: boolean
}, ExtArgs["result"]["oTP"]>

export type OTPSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  hashedCode?: boolean
  createdAt?: boolean
  expiresAt?: boolean
  consumed?: boolean
}, ExtArgs["result"]["oTP"]>

export type OTPSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  hashedCode?: boolean
  createdAt?: boolean
  expiresAt?: boolean
  consumed?: boolean
}, ExtArgs["result"]["oTP"]>

export type OTPSelectScalar = {
  id?: boolean
  email?: boolean
  hashedCode?: boolean
  createdAt?: boolean
  expiresAt?: boolean
  consumed?: boolean
}

export type OTPOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "hashedCode" | "createdAt" | "expiresAt" | "consumed", ExtArgs["result"]["oTP"]>

export type $OTPPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OTP"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    hashedCode: string
    createdAt: Date
    expiresAt: Date
    consumed: boolean
  }, ExtArgs["result"]["oTP"]>
  composites: {}
}

export type OTPGetPayload<S extends boolean | null | undefined | OTPDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OTPPayload, S>

export type OTPCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OTPFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OTPCountAggregateInputType | true
  }

export interface OTPDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OTP'], meta: { name: 'OTP' } }
  /**
   * Find zero or one OTP that matches the filter.
   * @param {OTPFindUniqueArgs} args - Arguments to find a OTP
   * @example
   * // Get one OTP
   * const oTP = await prisma.oTP.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OTPFindUniqueArgs>(args: Prisma.SelectSubset<T, OTPFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OTPClient<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OTP that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OTPFindUniqueOrThrowArgs} args - Arguments to find a OTP
   * @example
   * // Get one OTP
   * const oTP = await prisma.oTP.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OTPFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OTPFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OTPClient<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OTP that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OTPFindFirstArgs} args - Arguments to find a OTP
   * @example
   * // Get one OTP
   * const oTP = await prisma.oTP.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OTPFindFirstArgs>(args?: Prisma.SelectSubset<T, OTPFindFirstArgs<ExtArgs>>): Prisma.Prisma__OTPClient<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OTP that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OTPFindFirstOrThrowArgs} args - Arguments to find a OTP
   * @example
   * // Get one OTP
   * const oTP = await prisma.oTP.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OTPFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OTPFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OTPClient<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OTPS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OTPFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OTPS
   * const oTPS = await prisma.oTP.findMany()
   * 
   * // Get first 10 OTPS
   * const oTPS = await prisma.oTP.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const oTPWithIdOnly = await prisma.oTP.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OTPFindManyArgs>(args?: Prisma.SelectSubset<T, OTPFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OTP.
   * @param {OTPCreateArgs} args - Arguments to create a OTP.
   * @example
   * // Create one OTP
   * const OTP = await prisma.oTP.create({
   *   data: {
   *     // ... data to create a OTP
   *   }
   * })
   * 
   */
  create<T extends OTPCreateArgs>(args: Prisma.SelectSubset<T, OTPCreateArgs<ExtArgs>>): Prisma.Prisma__OTPClient<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OTPS.
   * @param {OTPCreateManyArgs} args - Arguments to create many OTPS.
   * @example
   * // Create many OTPS
   * const oTP = await prisma.oTP.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OTPCreateManyArgs>(args?: Prisma.SelectSubset<T, OTPCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OTPS and returns the data saved in the database.
   * @param {OTPCreateManyAndReturnArgs} args - Arguments to create many OTPS.
   * @example
   * // Create many OTPS
   * const oTP = await prisma.oTP.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OTPS and only return the `id`
   * const oTPWithIdOnly = await prisma.oTP.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OTPCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OTPCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OTP.
   * @param {OTPDeleteArgs} args - Arguments to delete one OTP.
   * @example
   * // Delete one OTP
   * const OTP = await prisma.oTP.delete({
   *   where: {
   *     // ... filter to delete one OTP
   *   }
   * })
   * 
   */
  delete<T extends OTPDeleteArgs>(args: Prisma.SelectSubset<T, OTPDeleteArgs<ExtArgs>>): Prisma.Prisma__OTPClient<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OTP.
   * @param {OTPUpdateArgs} args - Arguments to update one OTP.
   * @example
   * // Update one OTP
   * const oTP = await prisma.oTP.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OTPUpdateArgs>(args: Prisma.SelectSubset<T, OTPUpdateArgs<ExtArgs>>): Prisma.Prisma__OTPClient<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OTPS.
   * @param {OTPDeleteManyArgs} args - Arguments to filter OTPS to delete.
   * @example
   * // Delete a few OTPS
   * const { count } = await prisma.oTP.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OTPDeleteManyArgs>(args?: Prisma.SelectSubset<T, OTPDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OTPS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OTPUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OTPS
   * const oTP = await prisma.oTP.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OTPUpdateManyArgs>(args: Prisma.SelectSubset<T, OTPUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OTPS and returns the data updated in the database.
   * @param {OTPUpdateManyAndReturnArgs} args - Arguments to update many OTPS.
   * @example
   * // Update many OTPS
   * const oTP = await prisma.oTP.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OTPS and only return the `id`
   * const oTPWithIdOnly = await prisma.oTP.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OTPUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OTPUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OTP.
   * @param {OTPUpsertArgs} args - Arguments to update or create a OTP.
   * @example
   * // Update or create a OTP
   * const oTP = await prisma.oTP.upsert({
   *   create: {
   *     // ... data to create a OTP
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OTP we want to update
   *   }
   * })
   */
  upsert<T extends OTPUpsertArgs>(args: Prisma.SelectSubset<T, OTPUpsertArgs<ExtArgs>>): Prisma.Prisma__OTPClient<runtime.Types.Result.GetResult<Prisma.$OTPPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OTPS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OTPCountArgs} args - Arguments to filter OTPS to count.
   * @example
   * // Count the number of OTPS
   * const count = await prisma.oTP.count({
   *   where: {
   *     // ... the filter for the OTPS we want to count
   *   }
   * })
  **/
  count<T extends OTPCountArgs>(
    args?: Prisma.Subset<T, OTPCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OTPCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OTP.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OTPAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OTPAggregateArgs>(args: Prisma.Subset<T, OTPAggregateArgs>): Prisma.PrismaPromise<GetOTPAggregateType<T>>

  /**
   * Group by OTP.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OTPGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OTPGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OTPGroupByArgs['orderBy'] }
      : { orderBy?: OTPGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OTPGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOTPGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OTP model
 */
readonly fields: OTPFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OTP.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OTPClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OTP model
 */
export interface OTPFieldRefs {
  readonly id: Prisma.FieldRef<"OTP", 'String'>
  readonly email: Prisma.FieldRef<"OTP", 'String'>
  readonly hashedCode: Prisma.FieldRef<"OTP", 'String'>
  readonly createdAt: Prisma.FieldRef<"OTP", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"OTP", 'DateTime'>
  readonly consumed: Prisma.FieldRef<"OTP", 'Boolean'>
}
    

// Custom InputTypes
/**
 * OTP findUnique
 */
export type OTPFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * Filter, which OTP to fetch.
   */
  where: Prisma.OTPWhereUniqueInput
}

/**
 * OTP findUniqueOrThrow
 */
export type OTPFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * Filter, which OTP to fetch.
   */
  where: Prisma.OTPWhereUniqueInput
}

/**
 * OTP findFirst
 */
export type OTPFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * Filter, which OTP to fetch.
   */
  where?: Prisma.OTPWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OTPS to fetch.
   */
  orderBy?: Prisma.OTPOrderByWithRelationInput | Prisma.OTPOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OTPS.
   */
  cursor?: Prisma.OTPWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OTPS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OTPS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OTPS.
   */
  distinct?: Prisma.OTPScalarFieldEnum | Prisma.OTPScalarFieldEnum[]
}

/**
 * OTP findFirstOrThrow
 */
export type OTPFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * Filter, which OTP to fetch.
   */
  where?: Prisma.OTPWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OTPS to fetch.
   */
  orderBy?: Prisma.OTPOrderByWithRelationInput | Prisma.OTPOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OTPS.
   */
  cursor?: Prisma.OTPWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OTPS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OTPS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OTPS.
   */
  distinct?: Prisma.OTPScalarFieldEnum | Prisma.OTPScalarFieldEnum[]
}

/**
 * OTP findMany
 */
export type OTPFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * Filter, which OTPS to fetch.
   */
  where?: Prisma.OTPWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OTPS to fetch.
   */
  orderBy?: Prisma.OTPOrderByWithRelationInput | Prisma.OTPOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OTPS.
   */
  cursor?: Prisma.OTPWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OTPS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OTPS.
   */
  skip?: number
  distinct?: Prisma.OTPScalarFieldEnum | Prisma.OTPScalarFieldEnum[]
}

/**
 * OTP create
 */
export type OTPCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * The data needed to create a OTP.
   */
  data: Prisma.XOR<Prisma.OTPCreateInput, Prisma.OTPUncheckedCreateInput>
}

/**
 * OTP createMany
 */
export type OTPCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OTPS.
   */
  data: Prisma.OTPCreateManyInput | Prisma.OTPCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OTP createManyAndReturn
 */
export type OTPCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * The data used to create many OTPS.
   */
  data: Prisma.OTPCreateManyInput | Prisma.OTPCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OTP update
 */
export type OTPUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * The data needed to update a OTP.
   */
  data: Prisma.XOR<Prisma.OTPUpdateInput, Prisma.OTPUncheckedUpdateInput>
  /**
   * Choose, which OTP to update.
   */
  where: Prisma.OTPWhereUniqueInput
}

/**
 * OTP updateMany
 */
export type OTPUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OTPS.
   */
  data: Prisma.XOR<Prisma.OTPUpdateManyMutationInput, Prisma.OTPUncheckedUpdateManyInput>
  /**
   * Filter which OTPS to update
   */
  where?: Prisma.OTPWhereInput
  /**
   * Limit how many OTPS to update.
   */
  limit?: number
}

/**
 * OTP updateManyAndReturn
 */
export type OTPUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * The data used to update OTPS.
   */
  data: Prisma.XOR<Prisma.OTPUpdateManyMutationInput, Prisma.OTPUncheckedUpdateManyInput>
  /**
   * Filter which OTPS to update
   */
  where?: Prisma.OTPWhereInput
  /**
   * Limit how many OTPS to update.
   */
  limit?: number
}

/**
 * OTP upsert
 */
export type OTPUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * The filter to search for the OTP to update in case it exists.
   */
  where: Prisma.OTPWhereUniqueInput
  /**
   * In case the OTP found by the `where` argument doesn't exist, create a new OTP with this data.
   */
  create: Prisma.XOR<Prisma.OTPCreateInput, Prisma.OTPUncheckedCreateInput>
  /**
   * In case the OTP was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OTPUpdateInput, Prisma.OTPUncheckedUpdateInput>
}

/**
 * OTP delete
 */
export type OTPDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
  /**
   * Filter which OTP to delete.
   */
  where: Prisma.OTPWhereUniqueInput
}

/**
 * OTP deleteMany
 */
export type OTPDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OTPS to delete
   */
  where?: Prisma.OTPWhereInput
  /**
   * Limit how many OTPS to delete.
   */
  limit?: number
}

/**
 * OTP without action
 */
export type OTPDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OTP
   */
  select?: Prisma.OTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OTP
   */
  omit?: Prisma.OTPOmit<ExtArgs> | null
}
