
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PluginView` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PluginView
 * 
 */
export type PluginViewModel = runtime.Types.Result.DefaultSelection<Prisma.$PluginViewPayload>

export type AggregatePluginView = {
  _count: PluginViewCountAggregateOutputType | null
  _min: PluginViewMinAggregateOutputType | null
  _max: PluginViewMaxAggregateOutputType | null
}

export type PluginViewMinAggregateOutputType = {
  id: string | null
  pluginId: string | null
  ipAddress: string | null
  userAgent: string | null
  referrer: string | null
  country: string | null
  createdAt: Date | null
}

export type PluginViewMaxAggregateOutputType = {
  id: string | null
  pluginId: string | null
  ipAddress: string | null
  userAgent: string | null
  referrer: string | null
  country: string | null
  createdAt: Date | null
}

export type PluginViewCountAggregateOutputType = {
  id: number
  pluginId: number
  ipAddress: number
  userAgent: number
  referrer: number
  country: number
  createdAt: number
  _all: number
}


export type PluginViewMinAggregateInputType = {
  id?: true
  pluginId?: true
  ipAddress?: true
  userAgent?: true
  referrer?: true
  country?: true
  createdAt?: true
}

export type PluginViewMaxAggregateInputType = {
  id?: true
  pluginId?: true
  ipAddress?: true
  userAgent?: true
  referrer?: true
  country?: true
  createdAt?: true
}

export type PluginViewCountAggregateInputType = {
  id?: true
  pluginId?: true
  ipAddress?: true
  userAgent?: true
  referrer?: true
  country?: true
  createdAt?: true
  _all?: true
}

export type PluginViewAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PluginView to aggregate.
   */
  where?: Prisma.PluginViewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PluginViews to fetch.
   */
  orderBy?: Prisma.PluginViewOrderByWithRelationInput | Prisma.PluginViewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PluginViewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PluginViews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PluginViews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PluginViews
  **/
  _count?: true | PluginViewCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PluginViewMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PluginViewMaxAggregateInputType
}

export type GetPluginViewAggregateType<T extends PluginViewAggregateArgs> = {
      [P in keyof T & keyof AggregatePluginView]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePluginView[P]>
    : Prisma.GetScalarType<T[P], AggregatePluginView[P]>
}




export type PluginViewGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PluginViewWhereInput
  orderBy?: Prisma.PluginViewOrderByWithAggregationInput | Prisma.PluginViewOrderByWithAggregationInput[]
  by: Prisma.PluginViewScalarFieldEnum[] | Prisma.PluginViewScalarFieldEnum
  having?: Prisma.PluginViewScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PluginViewCountAggregateInputType | true
  _min?: PluginViewMinAggregateInputType
  _max?: PluginViewMaxAggregateInputType
}

export type PluginViewGroupByOutputType = {
  id: string
  pluginId: string
  ipAddress: string | null
  userAgent: string | null
  referrer: string | null
  country: string | null
  createdAt: Date
  _count: PluginViewCountAggregateOutputType | null
  _min: PluginViewMinAggregateOutputType | null
  _max: PluginViewMaxAggregateOutputType | null
}

type GetPluginViewGroupByPayload<T extends PluginViewGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PluginViewGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PluginViewGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PluginViewGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PluginViewGroupByOutputType[P]>
      }
    >
  >



export type PluginViewWhereInput = {
  AND?: Prisma.PluginViewWhereInput | Prisma.PluginViewWhereInput[]
  OR?: Prisma.PluginViewWhereInput[]
  NOT?: Prisma.PluginViewWhereInput | Prisma.PluginViewWhereInput[]
  id?: Prisma.StringFilter<"PluginView"> | string
  pluginId?: Prisma.StringFilter<"PluginView"> | string
  ipAddress?: Prisma.StringNullableFilter<"PluginView"> | string | null
  userAgent?: Prisma.StringNullableFilter<"PluginView"> | string | null
  referrer?: Prisma.StringNullableFilter<"PluginView"> | string | null
  country?: Prisma.StringNullableFilter<"PluginView"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PluginView"> | Date | string
}

export type PluginViewOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  referrer?: Prisma.SortOrderInput | Prisma.SortOrder
  country?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PluginViewWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PluginViewWhereInput | Prisma.PluginViewWhereInput[]
  OR?: Prisma.PluginViewWhereInput[]
  NOT?: Prisma.PluginViewWhereInput | Prisma.PluginViewWhereInput[]
  pluginId?: Prisma.StringFilter<"PluginView"> | string
  ipAddress?: Prisma.StringNullableFilter<"PluginView"> | string | null
  userAgent?: Prisma.StringNullableFilter<"PluginView"> | string | null
  referrer?: Prisma.StringNullableFilter<"PluginView"> | string | null
  country?: Prisma.StringNullableFilter<"PluginView"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PluginView"> | Date | string
}, "id">

export type PluginViewOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  referrer?: Prisma.SortOrderInput | Prisma.SortOrder
  country?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PluginViewCountOrderByAggregateInput
  _max?: Prisma.PluginViewMaxOrderByAggregateInput
  _min?: Prisma.PluginViewMinOrderByAggregateInput
}

export type PluginViewScalarWhereWithAggregatesInput = {
  AND?: Prisma.PluginViewScalarWhereWithAggregatesInput | Prisma.PluginViewScalarWhereWithAggregatesInput[]
  OR?: Prisma.PluginViewScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PluginViewScalarWhereWithAggregatesInput | Prisma.PluginViewScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PluginView"> | string
  pluginId?: Prisma.StringWithAggregatesFilter<"PluginView"> | string
  ipAddress?: Prisma.StringNullableWithAggregatesFilter<"PluginView"> | string | null
  userAgent?: Prisma.StringNullableWithAggregatesFilter<"PluginView"> | string | null
  referrer?: Prisma.StringNullableWithAggregatesFilter<"PluginView"> | string | null
  country?: Prisma.StringNullableWithAggregatesFilter<"PluginView"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PluginView"> | Date | string
}

export type PluginViewCreateInput = {
  id?: string
  pluginId: string
  ipAddress?: string | null
  userAgent?: string | null
  referrer?: string | null
  country?: string | null
  createdAt?: Date | string
}

export type PluginViewUncheckedCreateInput = {
  id?: string
  pluginId: string
  ipAddress?: string | null
  userAgent?: string | null
  referrer?: string | null
  country?: string | null
  createdAt?: Date | string
}

export type PluginViewUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referrer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PluginViewUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referrer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PluginViewCreateManyInput = {
  id?: string
  pluginId: string
  ipAddress?: string | null
  userAgent?: string | null
  referrer?: string | null
  country?: string | null
  createdAt?: Date | string
}

export type PluginViewUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referrer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PluginViewUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pluginId?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referrer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PluginViewCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  referrer?: Prisma.SortOrder
  country?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PluginViewMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  referrer?: Prisma.SortOrder
  country?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PluginViewMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pluginId?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  referrer?: Prisma.SortOrder
  country?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}



export type PluginViewSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pluginId?: boolean
  ipAddress?: boolean
  userAgent?: boolean
  referrer?: boolean
  country?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["pluginView"]>

export type PluginViewSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pluginId?: boolean
  ipAddress?: boolean
  userAgent?: boolean
  referrer?: boolean
  country?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["pluginView"]>

export type PluginViewSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pluginId?: boolean
  ipAddress?: boolean
  userAgent?: boolean
  referrer?: boolean
  country?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["pluginView"]>

export type PluginViewSelectScalar = {
  id?: boolean
  pluginId?: boolean
  ipAddress?: boolean
  userAgent?: boolean
  referrer?: boolean
  country?: boolean
  createdAt?: boolean
}

export type PluginViewOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pluginId" | "ipAddress" | "userAgent" | "referrer" | "country" | "createdAt", ExtArgs["result"]["pluginView"]>

export type $PluginViewPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PluginView"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pluginId: string
    ipAddress: string | null
    userAgent: string | null
    referrer: string | null
    country: string | null
    createdAt: Date
  }, ExtArgs["result"]["pluginView"]>
  composites: {}
}

export type PluginViewGetPayload<S extends boolean | null | undefined | PluginViewDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PluginViewPayload, S>

export type PluginViewCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PluginViewFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PluginViewCountAggregateInputType | true
  }

export interface PluginViewDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PluginView'], meta: { name: 'PluginView' } }
  /**
   * Find zero or one PluginView that matches the filter.
   * @param {PluginViewFindUniqueArgs} args - Arguments to find a PluginView
   * @example
   * // Get one PluginView
   * const pluginView = await prisma.pluginView.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PluginViewFindUniqueArgs>(args: Prisma.SelectSubset<T, PluginViewFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PluginViewClient<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PluginView that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PluginViewFindUniqueOrThrowArgs} args - Arguments to find a PluginView
   * @example
   * // Get one PluginView
   * const pluginView = await prisma.pluginView.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PluginViewFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PluginViewFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PluginViewClient<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PluginView that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginViewFindFirstArgs} args - Arguments to find a PluginView
   * @example
   * // Get one PluginView
   * const pluginView = await prisma.pluginView.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PluginViewFindFirstArgs>(args?: Prisma.SelectSubset<T, PluginViewFindFirstArgs<ExtArgs>>): Prisma.Prisma__PluginViewClient<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PluginView that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginViewFindFirstOrThrowArgs} args - Arguments to find a PluginView
   * @example
   * // Get one PluginView
   * const pluginView = await prisma.pluginView.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PluginViewFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PluginViewFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PluginViewClient<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PluginViews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginViewFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PluginViews
   * const pluginViews = await prisma.pluginView.findMany()
   * 
   * // Get first 10 PluginViews
   * const pluginViews = await prisma.pluginView.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pluginViewWithIdOnly = await prisma.pluginView.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PluginViewFindManyArgs>(args?: Prisma.SelectSubset<T, PluginViewFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PluginView.
   * @param {PluginViewCreateArgs} args - Arguments to create a PluginView.
   * @example
   * // Create one PluginView
   * const PluginView = await prisma.pluginView.create({
   *   data: {
   *     // ... data to create a PluginView
   *   }
   * })
   * 
   */
  create<T extends PluginViewCreateArgs>(args: Prisma.SelectSubset<T, PluginViewCreateArgs<ExtArgs>>): Prisma.Prisma__PluginViewClient<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PluginViews.
   * @param {PluginViewCreateManyArgs} args - Arguments to create many PluginViews.
   * @example
   * // Create many PluginViews
   * const pluginView = await prisma.pluginView.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PluginViewCreateManyArgs>(args?: Prisma.SelectSubset<T, PluginViewCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PluginViews and returns the data saved in the database.
   * @param {PluginViewCreateManyAndReturnArgs} args - Arguments to create many PluginViews.
   * @example
   * // Create many PluginViews
   * const pluginView = await prisma.pluginView.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PluginViews and only return the `id`
   * const pluginViewWithIdOnly = await prisma.pluginView.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PluginViewCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PluginViewCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PluginView.
   * @param {PluginViewDeleteArgs} args - Arguments to delete one PluginView.
   * @example
   * // Delete one PluginView
   * const PluginView = await prisma.pluginView.delete({
   *   where: {
   *     // ... filter to delete one PluginView
   *   }
   * })
   * 
   */
  delete<T extends PluginViewDeleteArgs>(args: Prisma.SelectSubset<T, PluginViewDeleteArgs<ExtArgs>>): Prisma.Prisma__PluginViewClient<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PluginView.
   * @param {PluginViewUpdateArgs} args - Arguments to update one PluginView.
   * @example
   * // Update one PluginView
   * const pluginView = await prisma.pluginView.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PluginViewUpdateArgs>(args: Prisma.SelectSubset<T, PluginViewUpdateArgs<ExtArgs>>): Prisma.Prisma__PluginViewClient<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PluginViews.
   * @param {PluginViewDeleteManyArgs} args - Arguments to filter PluginViews to delete.
   * @example
   * // Delete a few PluginViews
   * const { count } = await prisma.pluginView.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PluginViewDeleteManyArgs>(args?: Prisma.SelectSubset<T, PluginViewDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PluginViews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginViewUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PluginViews
   * const pluginView = await prisma.pluginView.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PluginViewUpdateManyArgs>(args: Prisma.SelectSubset<T, PluginViewUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PluginViews and returns the data updated in the database.
   * @param {PluginViewUpdateManyAndReturnArgs} args - Arguments to update many PluginViews.
   * @example
   * // Update many PluginViews
   * const pluginView = await prisma.pluginView.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PluginViews and only return the `id`
   * const pluginViewWithIdOnly = await prisma.pluginView.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PluginViewUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PluginViewUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PluginView.
   * @param {PluginViewUpsertArgs} args - Arguments to update or create a PluginView.
   * @example
   * // Update or create a PluginView
   * const pluginView = await prisma.pluginView.upsert({
   *   create: {
   *     // ... data to create a PluginView
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PluginView we want to update
   *   }
   * })
   */
  upsert<T extends PluginViewUpsertArgs>(args: Prisma.SelectSubset<T, PluginViewUpsertArgs<ExtArgs>>): Prisma.Prisma__PluginViewClient<runtime.Types.Result.GetResult<Prisma.$PluginViewPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PluginViews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginViewCountArgs} args - Arguments to filter PluginViews to count.
   * @example
   * // Count the number of PluginViews
   * const count = await prisma.pluginView.count({
   *   where: {
   *     // ... the filter for the PluginViews we want to count
   *   }
   * })
  **/
  count<T extends PluginViewCountArgs>(
    args?: Prisma.Subset<T, PluginViewCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PluginViewCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PluginView.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginViewAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PluginViewAggregateArgs>(args: Prisma.Subset<T, PluginViewAggregateArgs>): Prisma.PrismaPromise<GetPluginViewAggregateType<T>>

  /**
   * Group by PluginView.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginViewGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PluginViewGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PluginViewGroupByArgs['orderBy'] }
      : { orderBy?: PluginViewGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PluginViewGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPluginViewGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PluginView model
 */
readonly fields: PluginViewFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PluginView.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PluginViewClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PluginView model
 */
export interface PluginViewFieldRefs {
  readonly id: Prisma.FieldRef<"PluginView", 'String'>
  readonly pluginId: Prisma.FieldRef<"PluginView", 'String'>
  readonly ipAddress: Prisma.FieldRef<"PluginView", 'String'>
  readonly userAgent: Prisma.FieldRef<"PluginView", 'String'>
  readonly referrer: Prisma.FieldRef<"PluginView", 'String'>
  readonly country: Prisma.FieldRef<"PluginView", 'String'>
  readonly createdAt: Prisma.FieldRef<"PluginView", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PluginView findUnique
 */
export type PluginViewFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * Filter, which PluginView to fetch.
   */
  where: Prisma.PluginViewWhereUniqueInput
}

/**
 * PluginView findUniqueOrThrow
 */
export type PluginViewFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * Filter, which PluginView to fetch.
   */
  where: Prisma.PluginViewWhereUniqueInput
}

/**
 * PluginView findFirst
 */
export type PluginViewFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * Filter, which PluginView to fetch.
   */
  where?: Prisma.PluginViewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PluginViews to fetch.
   */
  orderBy?: Prisma.PluginViewOrderByWithRelationInput | Prisma.PluginViewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PluginViews.
   */
  cursor?: Prisma.PluginViewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PluginViews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PluginViews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PluginViews.
   */
  distinct?: Prisma.PluginViewScalarFieldEnum | Prisma.PluginViewScalarFieldEnum[]
}

/**
 * PluginView findFirstOrThrow
 */
export type PluginViewFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * Filter, which PluginView to fetch.
   */
  where?: Prisma.PluginViewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PluginViews to fetch.
   */
  orderBy?: Prisma.PluginViewOrderByWithRelationInput | Prisma.PluginViewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PluginViews.
   */
  cursor?: Prisma.PluginViewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PluginViews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PluginViews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PluginViews.
   */
  distinct?: Prisma.PluginViewScalarFieldEnum | Prisma.PluginViewScalarFieldEnum[]
}

/**
 * PluginView findMany
 */
export type PluginViewFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * Filter, which PluginViews to fetch.
   */
  where?: Prisma.PluginViewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PluginViews to fetch.
   */
  orderBy?: Prisma.PluginViewOrderByWithRelationInput | Prisma.PluginViewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PluginViews.
   */
  cursor?: Prisma.PluginViewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PluginViews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PluginViews.
   */
  skip?: number
  distinct?: Prisma.PluginViewScalarFieldEnum | Prisma.PluginViewScalarFieldEnum[]
}

/**
 * PluginView create
 */
export type PluginViewCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * The data needed to create a PluginView.
   */
  data: Prisma.XOR<Prisma.PluginViewCreateInput, Prisma.PluginViewUncheckedCreateInput>
}

/**
 * PluginView createMany
 */
export type PluginViewCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PluginViews.
   */
  data: Prisma.PluginViewCreateManyInput | Prisma.PluginViewCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PluginView createManyAndReturn
 */
export type PluginViewCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * The data used to create many PluginViews.
   */
  data: Prisma.PluginViewCreateManyInput | Prisma.PluginViewCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PluginView update
 */
export type PluginViewUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * The data needed to update a PluginView.
   */
  data: Prisma.XOR<Prisma.PluginViewUpdateInput, Prisma.PluginViewUncheckedUpdateInput>
  /**
   * Choose, which PluginView to update.
   */
  where: Prisma.PluginViewWhereUniqueInput
}

/**
 * PluginView updateMany
 */
export type PluginViewUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PluginViews.
   */
  data: Prisma.XOR<Prisma.PluginViewUpdateManyMutationInput, Prisma.PluginViewUncheckedUpdateManyInput>
  /**
   * Filter which PluginViews to update
   */
  where?: Prisma.PluginViewWhereInput
  /**
   * Limit how many PluginViews to update.
   */
  limit?: number
}

/**
 * PluginView updateManyAndReturn
 */
export type PluginViewUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * The data used to update PluginViews.
   */
  data: Prisma.XOR<Prisma.PluginViewUpdateManyMutationInput, Prisma.PluginViewUncheckedUpdateManyInput>
  /**
   * Filter which PluginViews to update
   */
  where?: Prisma.PluginViewWhereInput
  /**
   * Limit how many PluginViews to update.
   */
  limit?: number
}

/**
 * PluginView upsert
 */
export type PluginViewUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * The filter to search for the PluginView to update in case it exists.
   */
  where: Prisma.PluginViewWhereUniqueInput
  /**
   * In case the PluginView found by the `where` argument doesn't exist, create a new PluginView with this data.
   */
  create: Prisma.XOR<Prisma.PluginViewCreateInput, Prisma.PluginViewUncheckedCreateInput>
  /**
   * In case the PluginView was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PluginViewUpdateInput, Prisma.PluginViewUncheckedUpdateInput>
}

/**
 * PluginView delete
 */
export type PluginViewDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
  /**
   * Filter which PluginView to delete.
   */
  where: Prisma.PluginViewWhereUniqueInput
}

/**
 * PluginView deleteMany
 */
export type PluginViewDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PluginViews to delete
   */
  where?: Prisma.PluginViewWhereInput
  /**
   * Limit how many PluginViews to delete.
   */
  limit?: number
}

/**
 * PluginView without action
 */
export type PluginViewDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginView
   */
  select?: Prisma.PluginViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PluginView
   */
  omit?: Prisma.PluginViewOmit<ExtArgs> | null
}
