import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Geist_Mono } from "next/font/google";
import LoginModal from "@/components/shared/login";
import { ModalProvider } from "@/lib/hooks/useModal";
import { SessionProvider } from "next-auth/react";

const euclid = localFont({
  src: [
    {
      path: "../../public/fonts/EuclidCircularA-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/EuclidCircularA-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../../public/fonts/EuclidCircularA-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/EuclidCircularA-SemiBoldItalic.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../../public/fonts/EuclidCircularA-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/EuclidCircularA-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../public/fonts/EuclidCircularA-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/EuclidCircularA-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/EuclidCircularA-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/EuclidCircularA-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
  ],
  variable: "--font-euclid",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${euclid.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <ModalProvider>{children}</ModalProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
